editor:
  preview: false

backend:
  name: github
  repo: udit-001/resume
  base_url: https://sveltia-cms-auth.aurax.workers.dev
  skip_ci: true

media_folder: /media
public_folder: /media

singletons:
  - name: resume
    label: Resume
    file: src/main.typ
    icon: article
    fields:
      - name: body
        label: Resume
        widget: code
        output_code_only: true
        allow_language_selection: false
